auto: true
server: true
permalink: /:categories/:title
baseurl: /mapbox.js
version: v1.0.1
oldversion: v0.6.7
url: http://mapbox.com
title: mapbox.js
description: MapBox JavaScript API
rdiscount:
  extensions: [smart]
