api: https://www.mapbox.com
url: https://www.mapbox.com
permalink: /:categories/:title
baseurl: /mapbox.js
pygments: true
version: v1.4.0
masterbranch: master
oldversion: v0.6.7
title: mapbox.js
description: MapBox JavaScript API
rdiscount:
  extensions: [smart]
