url: https://www.mapbox.com
api: https://www.mapbox.com/core
tileApi: https://api.mapbox.com
source: docs
permalink: /:categories/:title/
baseurl: /mapbox.js
mapboxjs: v3.0.1
defaultid: 'mapbox.streets'
exclude: [dist]
future: true
