url: https://www.mapbox.cn
api: https://www.mapbox.cn/core
tileApi: https://api.mapbox.cn
source: docs
permalink: /:categories/:title/
baseurl: /mapbox.js
mapboxjs: v2.4.0
defaultid: 'mapbox.streets'
exclude: [dist]
future: true
