api: https://122e4e-mapbox.global.ssl.fastly.net
url: https://122e4e-mapbox.global.ssl.fastly.net
permalink: /:categories/:title
baseurl: /mapbox.js
pygments: true
mapboxjs: v1.6.1
defaultid: 'examples.map-9ijuk24y'
exclude: [node_modules]
rdiscount:
  extensions: [smart]
