api: https://122e4e-mapbox.global.ssl.fastly.net
url: https://122e4e-mapbox.global.ssl.fastly.net
permalink: /:categories/:title
baseurl: /mapbox.js
pygments: true
mapboxjs: v1.6.0
oldversion: v0.6.7
title: MapBox.js
defaultid: 'examples.map-9ijuk24y'
description: MapBox JavaScript API
exclude: [node_modules]
rdiscount:
  extensions: [smart]
