api: https://www.mapbox.com
url: https://www.mapbox.com
permalink: /:categories/:title
baseurl: /mapbox.js
pygments: true
version: v1.5.0
oldversion: v0.6.7
title: MapBox.js
defaultid: 'examples.map-9ijuk24y'
description: MapBox JavaScript API
rdiscount:
  extensions: [smart]
